apiVersion: v2
name: halan-app
appVersion: "1.1"
description: A Helm chart for halan application
version: 1.1.0
type: application
dependencies:
  - name: postgresql
    version: 10.5.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
